### ISSUE TITLE
Compability Error

### ISSUE THREAD

**Issue by AdmiralAwesome93** [MJSt/lib-java#3]
Hi Michael!

I´ve got troubles implementing your HashKdMapping in my project.

It says the following:
**Error:Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.
Error:...while parsing at/mjst/lib/java/geometry/collections/HashTreeKdMap$1.class**

I put the code in the gradle buildscripts inside the project, but it doesn´t seem to work. I worked with Version 1.6, but although I set the targetCompability + sourceCompability to 1.7, it still shows the error. 

Can you help me please?

best regards,
Robert

**Comment by mjStallinger** [comment]
Well, I set it to 1.8 - but I'll check if it can be compiled with 1.6 or 1.7 instead...
